#!/usr/bin/env bash

# Background Image
IMAGE="$HOME/.config/hypr/wallpapers/lockscreen.png"

# Colors
bg='00000000'		bgl='313244'		fg='d9e0ee'
red='f38ba8'	green='a6e3a1'		yellow='f9e2af'
blue='89b4fa'	magenta='cba6f7'	cyan='89dceb'
alpha='00000088'	orange='fab387'

# CMD
swaylock \
	\
	`# General` \
	--clock \
	--ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	--fade-in 0.2 \
	\
	`# Appearance` \
	--screenshots \
	--effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
	\
	`# Backspace Key` \
	--key-hl-color ${cyan} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	\
	`# Indicator` \
	--indicator \
	--indicator-radius 200 \
	--indicator-thickness 7 \
	\
	`# Inside Circle Colors` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	\
	`# Layout Colors` \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	\
	`# Line Colors` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	\
	`# Ring Colors` \
	--ring-color ${yellow} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	\
	`# Separator Color` \
	--separator-color ${bg} \
	\
	`# Text Colors` \
	--text-color ${orange} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg}
