#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

DIR="$HOME/.config/hypr"
rofi_cmd="rofi -kb-cancel MousePrimary,Escape -theme $DIR/rofi/themes/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

cdialog () {
	yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_cmd -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
		cdialog
		if [[ "$?" == 0 ]]; then
			systemctl poweroff
	    else
			exit
	    fi
        ;;
    $reboot)
		cdialog
		if [[ "$?" == 0 ]]; then
			systemctl reboot
	    else
			exit
	    fi
        ;;
    $lock)
        ~/.config/hypr/scripts/lockscreen
        ;;
    $suspend)
		cdialog
		if [[ "$?" == 0 ]]; then
			mpc -q pause
			amixer set Master mute
			betterlockscreen --suspend
	    else
			exit
	    fi
        ;;
    $logout)
		cdialog
		if [[ "$?" == 0 ]]; then
			kill -9 -1
	    else
			exit
	    fi
        ;;
esac

