#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## launch waybar with alt config

CONFIG="$HOME/.config/hypr/waybar/config"
STYLE="$HOME/.config/hypr/waybar/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi

# if [[ $(pgrep -x "waybar") = "waybar" ]];
# then
# killall waybar
# else
# if [[ $(pgrep -x "waybar") = "" ]];
# then
# waybar -b main-bar -c $CONFIG -s $STYLE > /dev/null 2>&1 &
# fi
# fi

# CONFIG_FILES="$HOME/.config/hypr/waybar/config $HOME/.config/hypr/waybar/style.css"

# trap "killall waybar" EXIT

# while true; do
#     waybar &
#     inotifywait -e create,modify $CONFIG_FILES
#     killall waybar
# done