#!/usr/bin/env bash

# Set the directory containing images
IMAGE_DIR="$HOME/.config/hypr/wallpapers/"

# Check if the directory exists and has images
if [[ ! -d $IMAGE_DIR ]] || [[ -z "$(ls -A $IMAGE_DIR/*.png $IMAGE_DIR/*.jpg 2>/dev/null)" ]]; then
	echo "Directory not found or invalid, or no images found: $IMAGE_DIR"
	exit 1
fi

# Settings
export SWWW_TRANSITION_POS=0.935,0.970
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=90
export SWWW_TRANSITION_DURATION=3
INTERVAL=600

# Functions
select_random_image() {
	find "$IMAGE_DIR" -type f \( -name "*.png" -o -name "*.jpg" \) -print0 | shuf -z -n1 | xargs -0 realpath
}

set_wallpaper() {
	swww img "$1" --transition-type grow
}

# Main loop
while true; do
	random_image=$(select_random_image)
	set_wallpaper "$random_image"
	sleep $INTERVAL
done

